src/SocialPro/MainBundle/Entity/PostEvent.php
<?php
/**
 * Created by PhpStorm.
 * User: Espoir
 * Date: 09/02/2017
 * Time: 22:40
 */

namespace SocialPro\MainBundle\Entity;
use Doctrine\ORM\Mapping as espoir;

/**
 * @espoir\Entity
 */
class PostEvent
{
    /**
     * @espoir\Id
     * @espoir\GeneratedValue
     * @espoir\Column(type="integer")
     */
   private  $id;

    /**
     * @espoir\Column(type="string")
     */
    private $status="En Cours";

    /**
     * @espoir\Column(type="string")
     */
    private $email="myAd@yahoo.fr";



    /**
     * @espoir\Column(type="integer",nullable=true)
     */
    private $tel=0;


    /**
     * @espoir\Column(type="integer")
     */
    private $nombrePlace=1;

    /**
     *@espoir\ManyToOne(targetEntity="SocialPro\UserBundle\Entity\User")
     *@espoir\JoinColumn(name="user_id", referencedColumnName="id",onDelete="CASCADE",nullable=true)
     */
    private $user;

    /**
     *@espoir\ManyToOne(targetEntity="Evenement")
     *@espoir\JoinColumn(name="id_event", referencedColumnName="id",onDelete="CASCADE",nullable=true)
     */
    private $id_event;


    /**
     * @espoir\Column(type="datetime")
     */
    private $date;

    /**
     * PostEvent constructor.
     * @param $date
     */
    public function __construct()
    {
        $this->date = new \DateTime('now');
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return mixed
     */
    public function getTel()
    {
        return $this->tel;
    }

    /**
     * @param mixed $tel
     */
    public function setTel($tel)
    {
        $this->tel = $tel;
    }

    /**
     * @return mixed
     */
    public function getNombrePlace()
    {
        return $this->nombrePlace;
    }

    /**
     * @param mixed $nombrePlace
     */
    public function setNombrePlace($nombrePlace)
    {
        $this->nombrePlace = $nombrePlace;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getIdEvent()
    {
        return $this->id_event;
    }

    /**
     * @param mixed $id_event
     */
    public function setIdEvent($id_event)
    {
        $this->id_event = $id_event;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email)
    {
        $this->email = $email;
    }




}

src/SocialPro/MainBundle/Form/PostEventType.php
<?php

namespace SocialPro\MainBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use SocialPro\MainBundle\Entity\Evenement;

class PostEventType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('status')->add('tel')->add('nombrePlace')->add('date')->add('user')
            ->add('id_event',EntityType::class,array('class'=>'SocialProMainBundle:Evenement',
                'choice_label'=>'nom'))
        ->add('ajouter',SubmitType::class);
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SocialPro\MainBundle\Entity\PostEvent'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'socialpro_mainbundle_postevent';
    }


}

src/SocialPro/MainBundle/Resources/views/PostEvent/afficherPostEvent.html.twig
{% extends "SocialProMainBundle::layout.html.twig" %}
{% block title %} - Afficher PostEvent {% endblock %}
{% block contenent %}
    <div class="div" style="margin-top:30px;margin-bottom:30px;margin-left: 15%; margin-right: 15%; padding: 20px; border-radius: 15px; background-color: white; border: solid 1px; border-color: darkgrey;">
   <center><h1>Liste  des candidatures pour les evenements </h1></center>

        <table class="table table-striped table-advance table-hover">

        <tbody>
        <tr>
            <th> Titre</th>
            <th> Etat de la demande</th>
            <th> Nombre de place </th>
            <th> Telephone </th>
            <th>email</th>
            <td>Action</td><th>Date</th>
        </tr>
        {% for espoir in modele %}

        <tr><td>{{ espoir.idEvent.nom }}</td>
            <td>{{ espoir.status }}</td>
            <td>{{ espoir.nombrePlace }}</td>
            <td>{{ espoir.tel }}</td>
            <td><a href="">{{ espoir.email }}</a></td> <td style="background-color: mintcream">{{ espoir.date|date }}</td><td>
                <div >
                    <a  href="{{ path('accepterMyPostEvent',{'id':espoir.id}) }}"><input type="button" value="Accepter" style="width: 90px;background-color: #21f8f8;"></a>
                    <a  href="{{ path('supprimer_PostEmploi',{'id':espoir.id}) }}"><input type="button" value="supprimer" style="width: 90px;background-color: #2aadde"></a>
                    <a  href="{{ path('refuserMyPostEvent',{'id':espoir.id}) }}"><input type="button" value="Refuser" style="width: 90px;background-color: #FDF5CE"></a>
                </div></td></tr>
        </tbody>



        {% endfor %}



    </table>


    </div><br><br>


{% endblock %}

src/SocialPro/MainBundle/Resources/views/PostEvent/modifierPostEvent.html.twig
{% extends "SocialProMainBundle::layout.html.twig" %}
{% block title %} - Ajouter Emploi {% endblock %}
{% block contenent %}



    <script type="text/javascript" src=""></script>
    <style type="text/css">
        .div {
            /* Pour le centrer dans la page */
            margin: 0 auto;
            width: 1100px;
            /* Pour voir les limites du formulaire */




        }
        .deuxvaleurs {
            border-spacing: 5px 10px;
        }
        .label {

        }

    </style>


            <h1>Ajouter Un Evenement</h1>
            <center></center><br>

            {{ form_start(form) }}

            <div class="">
                <table  class="deuxvaleurs">
                    <tr style="display: none;"><td class="label">Etade la demande :</td>
                        <td>{{ form_widget(form.status) }}</td>
                    </tr>
                    <tr style="display: none;"><td class="label">Etade la demande :</td>
                        <td>{{ form_widget(form.id_event) }}</td>
                    </tr>
                    <tr style="display: none"><td class="label">Email :</td>
                        <td>{{ form_widget(form.user) }}</td>
                    </tr>
                    <tr><td class="label">Telephone :</td>
                        <td>{{ form_widget(form.tel) }}</td>
                    </tr>
                    <tr><td class="label">Nombre de place :</td>
                        <td>{{ form_widget(form.nombrePlace) }}</td>
                    </tr>
                    <tr  style="display: none;"><td  style="display: none" class="label">Utlisateur :</td>
                        <td style="display: none">{{ form_widget(form.user) }}</td>
                    </tr>


                    <tr style="display: none"><td class="label">Date :</td>
                        <td>{{ form_widget(form.date) }}</td>
                    </tr>
                    <tr  style="display: none"  >
                        <td align="center">L'utilisateur: </td>
                        <td align="center"> {{app.user.username}} </td>
                    </tr>
                </table>
                <p>{{ form_widget(form.ajouter) }}</p>

            </div>

            {{ form_end(form) }}

{% endblock %}

src/SocialPro/MainBundle/Resources/views/PostEvent/rechercherPostEvent.html.twig
{% extends "SocialProMainBundle::layout.html.twig" %}
{% block title %} - Afficher Emploi {% endblock %}
{% block contenent %}
    <html>
    <head>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
        <meta charset="utf-8">
        <style>
            html, body {
                height: 100%;
                margin: 0;
                padding: 0;
            }
            #map {
                height: 100%;
            }
            .controls {
                margin-top: 10px;
                border: 1px solid transparent;
                border-radius: 2px 0 0 2px;
                box-sizing: border-box;
                -moz-box-sizing: border-box;
                height: 32px;
                outline: none;
                box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
            }

            #pac-input {
                background-color: #fff;
                font-family: Roboto;
                font-size: 15px;
                font-weight: 300;
                margin-left: 12px;
                padding: 0 11px 0 13px;
                text-overflow: ellipsis;
                width: 300px;
            }

            #pac-input:focus {
                border-color: #4d90fe;
            }

            .pac-container {
                font-family: Roboto;
            }

            #type-selector {
                color: #fff;
                background-color: #4d90fe;
                padding: 5px 11px 0px 11px;
            }

            #type-selector label {
                font-family: Roboto;
                font-size: 13px;
                font-weight: 300;
            }

        </style>
        <title>Places Searchbox</title>
        <style>
            #target {
                width: 345px;
            }
        </style>
    </head>
    <body>

    <center>
        <div  align="center" class="div" style="margin-top:30px;margin-bottom:30px;margin-left: 15%; margin-right: 15%; padding: 20px; border-radius: 15px; background-color: white; border: solid 1px; border-color: darkgrey;width:900px;">
            <h2>rechecher Post Event</h2>
            {{ form(form) }}
            <h1>Details s Evenement </h1>
            <marquee><p>Veillez lire avec plus d'attention !!!</p></marquee>

            <table class="table table-striped table-advance table-hover">

                <tbody>
                <tr>
                    <th> Nom</th>
                    <th> Etat de la demande</th>
                    <th> Telephone</th>
                    <th> Nombre de place</th>
                    <th>email</th>
                    <td>Fait le</td><td>Action</td>
                </tr>

                {%  for modele in modele%}
                <tr><td>{{  modele.idEvent.nom }}</td><td>{{ modele.status }}</td> <td>{{ modele.tel }}</td>
                    <td>{{ modele.nombrePlace }}</td><td>{{  modele.email }}</td> <td style="background-color: mintcream">{{  modele.date|date }}</td><td>
                        <div >
                            <a  href="{{ path('modifierMyPostEvent',{'id':modele.id}) }}"><input type="button" value="modifier" style="width: 90px;background-color: #2aadde"></a>
                            <a  href="{{ path('supprimerMyPostEvent',{'id':modele.id}) }}"><input type="button" value="supprimer" style="width: 90px;background-color: #2aadde"></a>
                        </div>
                    </td></tr>
                </tbody>


                {% endfor %}

            </table><br>



            <br><br>

        </div></center>
    </body>
    </html>
{% endblock %}