src/SocialPro/MainBundle/Entity/Evenement.php
<?php
/**
 * Created by PhpStorm.
 * User: Espoir
 * Date: 01/02/2017
 * Time: 15:18
 */

namespace SocialPro\MainBundle\Entity;
use Doctrine\ORM\Mapping as espoir;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @espoir\Entity
 */
class Evenement
{
    /**
     * @espoir\Column(type="integer")
     * @espoir\Id
     * @espoir\GeneratedValue
     */
    private $id;


    /**
     * @espoir\Column(type="string",nullable=true)
     */
    private $nom;

    /**
     * @espoir\Column(type="text",nullable=true)
     */
    private $description;


    /**
     * @espoir\Column(type="string",nullable=true)
     */
    private $lieu;


    /**
     * @espoir\Column(type="string",nullable=true)
     */
    private $theme;

    /**
     * @espoir\Column(type="integer",nullable=true)
     */
    private $nombre_place;

    /**
     * @espoir\Column(type="datetime",nullable=true)
     */
    private $date_debut;


    /**
     * @espoir\Column(type="datetime",nullable=true)
     */
    private $date_fin;

    /**
     * @espoir\Column(type="datetime")
     */
    private $date;


    /**
     * @var float     Latitude of the position
     *
     * @espoir\Column(name="lat", type="float", nullable=true)
     */
    protected $lat;

    /**
     * @var float     Longitude of the position
     *
     * @espoir\Column(name="lng", type="float", nullable=true)
     */
    protected $lng;


    /**
     *@espoir\ManyToOne(targetEntity="SocialPro\UserBundle\Entity\User")
     *@espoir\JoinColumn(name="user_id", referencedColumnName="id",onDelete="CASCADE",nullable=true)
     */
    private $user;


    public function __construct()
    {
        $this->date = new \DateTime('now');
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param mixed $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return mixed
     */
    public function getLieu()
    {
        return $this->lieu;
    }

    /**
     * @param mixed $lieu
     */
    public function setLieu($lieu)
    {
        $this->lieu = $lieu;
    }

    /**
     * @return mixed
     */
    public function getTheme()
    {
        return $this->theme;
    }

    /**
     * @param mixed $theme
     */
    public function setTheme($theme)
    {
        $this->theme = $theme;
    }

    /**
     * @return mixed
     */
    public function getNombrePlace()
    {
        return $this->nombre_place;
    }

    /**
     * @param mixed $nombre_place
     */
    public function setNombrePlace($nombre_place)
    {
        $this->nombre_place = $nombre_place;
    }

    /**
     * @return mixed
     */
    public function getDateDebut()
    {
        return $this->date_debut;
    }

    /**
     * @param mixed $date_debut
     */
    public function setDateDebut($date_debut)
    {
        $this->date_debut = $date_debut;
    }

    /**
     * @return mixed
     */
    public function getDateFin()
    {
        return $this->date_fin;
    }

    /**
     * @param mixed $date_fin
     */
    public function setDateFin($date_fin)
    {
        $this->date_fin = $date_fin;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @return mixed
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * @param mixed $lat
     */
    public function setLat($lat)
    {
        $this->lat = $lat;
    }

    /**
     * @return float
     */
    public function getLng()
    {
        return $this->lng;
    }

    /**
     * @param float $lng
     */
    public function setLng($lng)
    {
        $this->lng = $lng;
    }



}

src/SocialPro/MainBundle/Form/EvenementType.php
<?php

namespace SocialPro\MainBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('nom')
            ->add('description',TextareaType::class,array('attr' => array('rows' => '10','cols' => '50')))
            ->add('lieu')->add('theme')->add('nombre_place')->add('date_debut')->add('date_fin')->add('date')
            ->add('lat')->add('lng')->add('user')
            ->add('ajouter',SubmitType::class);;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SocialPro\MainBundle\Entity\Evenement'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'socialpro_mainbundle_evenement';
    }


}

src/SocialPro/MainBundle/Controller/EvenementController.php
<?php

namespace SocialPro\MainBundle\Controller;


use SocialPro\MainBundle\Entity\PostEvent;
use SocialPro\MainBundle\Form\PostEventType;
use SocialPro\MainBundle\Form\rechercherEmploiType;
use SocialPro\MainBundle\Form\rechercherPostEvent;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use SocialPro\MainBundle\Entity\Evenement;
use SocialPro\MainBundle\Form\EvenementType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File;

class EvenementController extends Controller
{
    public function indexAction($name)
    {
        return $this->render('', array('name' => $name));
    }

    public function ajouterEvenementAction(Request $la_requetteEspoir){

        $modele=new  Evenement();

        // $user = $this->get('security.context')->getToken()->getUser();

        $form = $this->createForm(EvenementType::class,$modele);
        $form->handleRequest($la_requetteEspoir);
        if($form->isValid()){


            // $model->setUser($user);
            // $file stores the uploaded PDF file
            /** @var (Symfony\Component\HttpFoundation\File\UploadedFile $file) */
            //   $file=$modele->getImage();
            //   $fileName = $this->get('app.image_uploader')->upload($file);

            // Update the 'brochure' property to store the PDF file name
            // instead of its contents

            //   $modele->setImage($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($modele);
            $em->flush();
            return $this->redirectToRoute('afficher_Evenement_ent');
        }
        return $this->render('SocialProMainBundle:Evenement:ajoutEvenement.html.twig',array('form'=>$form->createView()));


    }
    public function  JoindreEvenementAction( $id){



        $user = $this->get('security.token_storage')->getToken()->getUser();
        $em=$this->getDoctrine()->getManager();
        $modele2 = $em->getRepository("SocialProUserBundle:User")->find($user);

        $em = $this->getDoctrine()->getManager();
        $modele = $em->getRepository("SocialProMainBundle:Evenement")->find($id);

        $modele2->setEvenements($modele);
        $em=$this->getDoctrine()->getManager();
        $em->persist($modele2);
        $em->flush();
        return $this->redirectToRoute('afficher_Evenement');

    }
    public function MapAction(){
        return $this->render('@SocialProMain/Evenement/try.html.twig');
    }
    public function Map1Action($id){

        $modele=new Evenement();
        $em=$this->getDoctrine()->getManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->find($id);
        return $this->render('SocialProMainBundle:Evenement:placeDetails.html.twig',array('modele'=>$modele));
    }


    public function Map1PersonneAction($id){

        $modele=new Evenement();
        $em=$this->getDoctrine()->getManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->find($id);
        return $this->render('SocialProMainBundle:Evenement:placeDetailsPersonne.html.twig',array('modele'=>$modele));
    }

    public  function postulerEvenementAction($id){

        $username=$this->get('security.token_storage')->getToken()->getUser();
        $userManager = $this->container->get('fos_user.user_manager');
        //$username="blabla";




        $em=$this->getDoctrine()->getEntityManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->find($id);

        //
        $postEvenement = new PostEvent();
        $modele->getId();
        // $id_emploi=$modele->getId();
        // $postEmploi->setIdEmploi($id_emp);
        $postEvenement->setIdEvent($modele);

        $id_user=$modele->getUser();
        $postEvenement->setUser($id_user);

        $postEvenement->setStatus("En cours");
        $postEvenement->setNombrePlace(1);
        $postEvenement->setTel(null);
        $postEvenement->setEmail($username);
        $postEvenement->setDate(new \DateTime('now'));
        $em->persist($postEvenement);
        $em->flush();




        return $this->redirectToRoute('afficher_Evenement');
    }
    public  function postulerEvenementPersonneAction($id){

        $username=$this->get('security.token_storage')->getToken()->getUser();
        $userManager = $this->container->get('fos_user.user_manager');
        //$username="blabla";




        $em=$this->getDoctrine()->getEntityManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->find($id);

        //
        $postEvenement = new PostEvent();
        $modele->getId();
        // $id_emploi=$modele->getId();
        // $postEmploi->setIdEmploi($id_emp);
        $postEvenement->setIdEvent($modele);

        $id_user=$modele->getUser();
        $postEvenement->setUser($id_user);

        $postEvenement->setStatus("En cours");
        $postEvenement->setNombrePlace(1);
        $postEvenement->setTel(null);
        $postEvenement->setEmail($username);
        $postEvenement->setDate(new \DateTime('now'));
        $em->persist($postEvenement);
        $em->flush();




        return $this->redirectToRoute('afficher_Evenement_personne');
    }



    public function abonnerEvenementAction( Request $ma_requette,$id){
        $modele=new  Evenement();

        // $user = $this->get('security.context')->getToken()->getUser();

        $form = $this->createForm(EvenementType::class,$modele);
        $form->handleRequest($ma_requette);
        if($form->isValid()){
            $em = $this->getDoctrine()->getManager();
            // $model->setUser($user);
            $em->persist($modele);
            $em->flush();
            return $this->redirectToRoute('afficher_Evenement');
        }
        return $this->render('SocialProMainBundle:Evenement:ajoutEvenement.html.twig',array('form'=>$form->createView()));

        $em=$this->getDoctrine()->getManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->find($id);

        $em->remove($modele);
        $em->flush();

        return $this->redirectToRoute('afficher_Evenement');

    }


    public  function afficherEvenementAction(){
        $em=$this->getDoctrine()->getEntityManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->findAll();
        return $this->render('SocialProMainBundle:Evenement:afficherMesEvenement.html.twig',array('modele'=>$modele));
    }
    public  function afficherEvenementPersonneAction(){
        $em=$this->getDoctrine()->getEntityManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->findAll();
        return $this->render('SocialProMainBundle:Evenement:afficherMesEvenementPersonne.html.twig',array('modele'=>$modele));
    }
    public function  supprimerEvenementAction($id){
        $em=$this->getDoctrine()->getManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->find($id);

        $em->remove($modele);
        $em->flush();

        return $this->redirectToRoute('afficher_Evenement_ent');
    }


    public  function  modifierEvenementAction(Request $requette,$id){
        $em=$this->getDoctrine()->getManager();
        $modele=$em->getRepository('SocialProMainBundle:Evenement')->find($id);

        $form=$this->createForm(EvenementType::class,$modele);
        $form->handleRequest($requette);
        if($form->isValid()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($modele);
            $em->flush();

            return $this->redirectToRoute('afficher_Evenement_ent');
        }
        return $this->render('SocialProMainBundle:Evenement:modifierEvenement.html.twig',array('form'=>$form->createView()));
    }
    public  function rechercherEvenementAction(Request $requette){
        $modele=new Evenement();
        $em=$this->getDoctrine()->getEntityManager();
        $form=$this->createFormBuilder($modele)
            ->add('nom')
            ->add('chercher',SubmitType::class)
            ->getForm();

        $form->handleRequest($requette);
        if($form->isValid()){
            $modele=$em->getRepository('SocialProMainBundle:Evenement')->findBy(array('nom'=>$modele->getNom()));
        }

        return $this->render('SocialProMainBundle:Evenement:rechercherEvenement.html.twig',array('form'=>$form->createView(),'modele'=>$modele));
    }

    public function AfficherPostEventAction(){
        $em=$this->getDoctrine()->getManager();
        $modele=$em->getRepository('SocialProMainBundle:PostEvent')->findAll();

        return $this->render('SocialProMainBundle:PostEvent:afficherPostEvent.html.twig',array('modele'=>$modele));


    }

    public function supprimerPostEventAction($id){
        $em=$this->getDoctrine()->getManager();
        $modele=$em->getRepository('SocialProMainBundle:PostEvent')->find($id);

        $em->remove($modele);
        $em->flush();

        return $this->redirectToRoute('AfficherPostEvent');


    }
    public function  RefuserEvenementAction($id){
        $em=$this->getDoctrine()->getManager();
        $etat=$em->getRepository('SocialProMainBundle:PostEvent')->find($id);
        $modeles=$em->getRepository('SocialProMainBundle:PostEvent')->findAll();
        $etat->setStatus('Refuser');
        $em->persist($etat);

        $em->flush();

       return  $this->redirect($this->generateUrl('AfficherPostEvent'));

    }

    public function AccepterEvenementAction($id){
        $em=$this->getDoctrine()->getManager();
        $etat=$em->getRepository('SocialProMainBundle:PostEvent')->find($id);
        $modeles=$em->getRepository('SocialProMainBundle:PostEvent')->findAll();
        $etat->setStatus('Accepter');
        $em->persist($etat);

        $em->flush();

         return $this->redirect($this->generateUrl('AfficherPostEvent'));
    }
    public  function rechercherPostEvenementAction(Request $requette){

src/SocialPro/MainBundle/Resources/views/Evenement/afficherEvenement.html.twig
{% extends "SocialProMainBundle::layout.html.twig" %}
{% block title %} - Afficher Evenement {% endblock %}
{% block contenent %}

    <style>
        .zoomable-image{display:block;-webkit-transition:-webkit-transform 1s cubic-bezier(.23,1,.32,1);-webkit-transform:translateZ(0);-ms-transform:translateZ(0)}
        .zoomable-image:hover{-webkit-transform:scale3d(1.05,1.05,1.05);-ms-transform:scale3d(1.05,1.05,1.05)}
        button:not(.sauf),input[type=submit]  {
            /* border: 1px solid #3079ed; */
            border: 0px;
            color: white;

            background-color: #00bfa5;
            padding: 7px;

            font-size: 14px;
            /* background-image: -webkit-gradient(linear, 0 0, 0 100%,   from(#4d90fe), to(#4787ed)); */
        }

        textarea{

            height: 44px;
            font-size: 16px;
            width: 50%;
            margin-bottom: 10px;
            -webkit-appearance: none;
            box-shadow: #0a0a0a 5px 5px 1px;
            border: 1px solid #26a69a ;

            /* border-radius: 2px; */
            padding: 0 8px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
        }

    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
    <script>
        $(document).ready(function() {

//Lorsque vous cliquez sur un lien de la classe poplight et que le href commence par #
            $('a.poplight[href^=#]').click(function() {
                var popID = $(this).attr('rel'); //Trouver la pop-up correspondante
                var popURL = $(this).attr('href'); //Retrouver la largeur dans le href

//Récupérer les variables depuis le lien
                var query= popURL.split('?');
                var dim= query[1].split('&amp;');
                var popWidth = dim[0].split('=')[1]; //La première valeur du lien

//Faire apparaitre la pop-up et ajouter le bouton de fermeture
                $('#' + popID).fadeIn().css({
                    'width': Number(popWidth)
                })
                        .prepend('<a href="#" class="close"><img src="{{ asset('Espoir/image/close_pop.png') }}" class="btn_close" title="Fermer" alt="Fermer" /></a>');

//Récupération du margin, qui permettra de centrer la fenêtre - on ajuste de 80px en conformité avec le CSS
                var popMargTop = ($('#' + popID).height() + 80) / 2;
                var popMargLeft = ($('#' + popID).width() + 80) / 2;

//On affecte le margin
                $('#' + popID).css({
                    'margin-top' : -popMargTop,
                    'margin-left' : -popMargLeft
                });

//Effet fade-in du fond opaque
                $('body').append('<div id="fade"></div>'); //Ajout du fond opaque noir
//Apparition du fond - .css({'filter' : 'alpha(opacity=80)'}) pour corriger les bogues de IE
                $('#fade').css({'filter' : 'alpha(opacity=80)'}).fadeIn();

                return false;
            });

//Fermeture de la pop-up et du fond
            $('a.close, #fade').live('click', function() { //Au clic sur le bouton ou sur le calque...
                $('#fade , .popup_block').fadeOut(function() {
                    $('#fade, a.close').remove();  //...ils disparaissent ensemble
                });
                return false;
            });
        });
    </script>
     <div class="div" style="margin-top:30px;margin-bottom:30px;margin-left: 15%; margin-right: 15%; padding: 20px; border-radius: 15px; background-color: white; border: solid 1px; border-color: darkgrey;">

<center>
    <h1>Afficher les  Evenements </h1>
    <table class="table table-striped table-advance table-hover">

        <tbody>
        <tr>
            <th> Evenement</th>
            <th> Theme</th>
            <th> Lieu</th>
            <th> Fait le </th><td>Action</td>
        </tr>
        {% for espoir in modele %}


        <tr>
            <td style="background-color: mintcream">{{ espoir.nom }}</td>
            <td style="background-color: mintcream">{{ espoir.theme }}</td>
            <td style="background-color: mintcream">{{ espoir.lieu }}</td>
            <td style="background-color: mintcream">{{ espoir.date|date }}</td><td>
           <div >
                  <a href="#?w=500" rel="{{ espoir.id }}" class="poplight"><input type="button" value="visiter" style="width: 70px;background-color: #21f8f8;"></a>
                    <a  href="{{ path('postulerEvenement_Evenement',{'id':espoir.id}) }}"><input type="button" value="signer" style="width: 70px;background-color: #2aadde"></a>
                </div></td>
        </tr>
        </tbody>
        {% endfor %}
    </table>

    </div><br><br>
    {% for espoir in modele %}



    <div id="{{ espoir.id }}" class="popup_block">
        <center></center>

        <div  > <center>  <h3 style="color:green">{{ espoir.nom }} </h3> </center><!--<h3> <span  style="color:#26a69a">ID:</span>  <span style="opacity:0.5"> {{ espoir.id }} </span></h3>--> <h4><span  style="color:#26a69a">Categorie:</span>   {{ espoir.nombrePlace }} </h4> <h4><span  style="color:#26a69a">proprietaire:</span>   {{ espoir.nombrePlace }}</h4> <h4><span  style="color:#26a69a">Description:</span>   {{ espoir.description }} </h4><h4><span  style="color:#26a69a">Prix(estimation):</span>   {{ espoir.description }} DT</h4></div>


        <center><button class="sauf" style="background-color:#26a69a "><a type="button" style="color: white" href="">supprimer </a> </button><button class="sauf" style="background-color:#26a69a "><a type="button" style="color: white" href="">modifier </a> </button></center>
    </div>
    </div>
    {% endfor %}




    <style class="poplight">

        #fade { /*--Masque opaque noir de fond--*/
            display: none; /*--masqué par défaut--*/
            background: #000;
            position: fixed; left: 0; top: 0;
            width: 100%; height: 100%;
            opacity: .80;
            z-index: 9999;
        }
        .popup_block{
            display: none; /*--masqué par défaut--*/
            background: #fff;
            padding: 20px;
            border: 20px solid #ddd;
            float: left;
            font-size: 1.2em;
            position: fixed;
            top: 50%; left: 50%;
            z-index: 99999;
            /*--Les différentes définitions de Box Shadow en CSS3--*/
            -webkit-box-shadow: 0px 0px 20px #000;
            -moz-box-shadow: 0px 0px 20px #000;
            box-shadow: 0px 0px 20px #000;
            /*--Coins arrondis en CSS3--*/
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
        }
        img.btn_close {
            float: right;
            margin: -55px -55px 0 0;
        }
        /*--Gérer la position fixed pour IE6--*/
        *html #fade {
            position: absolute;
        }
        *html .popup_block {
            position: absolute;
        }

    </style>
</center>

{% endblock %}

src/SocialPro/MainBundle/Resources/views/Evenement/afficherEvenementAvecMap.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        #map {
            height: 100%;
        }
        .controls {
            margin-top: 10px;
            border: 1px solid transparent;
            border-radius: 2px 0 0 2px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
            height: 32px;
            outline: none;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        }

        #pac-input {
            background-color: #fff;
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
            margin-left: 12px;
            padding: 0 11px 0 13px;
            text-overflow: ellipsis;
            width: 300px;
        }

        #pac-input:focus {
            border-color: #4d90fe;
        }

        .pac-container {
            font-family: Roboto;
        }

        #type-selector {
            color: #fff;
            background-color: #4d90fe;
            padding: 5px 11px 0px 11px;
        }

        #type-selector label {
            font-family: Roboto;
            font-size: 13px;
            font-weight: 300;
        }

    </style>
    <title>Places Searchbox</title>
    <style>
        #target {
            width: 345px;
        }
    </style>
</head>
<body>
<center>
    <div style="width: 800px;height: 600px">
        <input id="pac-input" class="controls" type="text" placeholder="Search Box">
        <div id="map"></div>
        <script>
            // This example adds a search box to a map, using the Google Place Autocomplete
            // feature. People can enter geographical searches. The search box will return a
            // pick list containing a mix of places and predicted search terms.

            function initAutocomplete() {
                var map = new google.maps.Map(document.getElementById('map'), {
                    center: {lat: -80.363, lng: 131.044 },
                    zoom: 15,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                });

                // Create the search box and link it to the UI element.
                var input = document.getElementById('pac-input');
                var searchBox = new google.maps.places.SearchBox(input);
                map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

                // Bias the SearchBox results towards current map's viewport.
                map.addListener('bounds_changed', function() {
                    searchBox.setBounds(map.getBounds());
                });

                var markers = [];
                // [START region_getplaces]
                // Listen for the event fired when the user selects a prediction and retrieve
                // more details for that place.
                searchBox.addListener('places_changed', function() {
                    var places = searchBox.getPlaces();

                    if (places.length == 0) {
                        return;
                    }

                    // Clear out the old markers.
                    markers.forEach(function(marker) {
                        marker.setMap(null);
                    });
                    markers = [];

                    // For each place, get the icon, name and location.
                    var bounds = new google.maps.LatLngBounds();
                    places.forEach(function(place) {
                        var icon = {
                            url: place.icon,
                            size: new google.maps.Size(71, 71),
                            origin: new google.maps.Point(0, 0),
                            anchor: new google.maps.Point(17, 34),
                            scaledSize: new google.maps.Size(25, 25)
                        };

                        // Create a marker for each place.
                        markers.push(new google.maps.Marker({
                            map: map,
                            icon: icon,
                            title: place.name,
                            position: place.geometry.location
                        }));

                        if (place.geometry.viewport) {
                            // Only geocodes have viewport.
                            bounds.union(place.geometry.viewport);
                        } else {
                            bounds.extend(place.geometry.location);
                        }
                    });
                    map.fitBounds(bounds);
                });
                // [END region_getplaces]
            }


        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCDST6BTwCnHvix1nBZuWO8SQtpmyu6-ys&libraries=places&callback=initAutocomplete"
                async defer></script></div></center>
<center>
    <h1>Details s Evenement </h1>
    <div class="div">
        <table border="1" style="background-color: transparent" class="deuxvaleurs">
            <tr><td class="label">Type :</td>
                <td style="background-color: mintcream">{{ modele.nom }}</td>
            </tr>
            <tr><td class="label">De la part de :</td>
                <td style="background-color: mintcream">{{ modele.theme }}</td>
            </tr>
            <tr><td class="label">Le code de l'object :</td>
                <td style="background-color: mintcream">{{ modele.description }}</td>
            </tr>
            <tr><td class="label">Description :</td>
                <td style="background-color: mintcream">{{ modele.lieu }}</td>
            </tr>
            <tr><td class="label">Reponse :</td>
                <td style="background-color: lightsalmon">{{ modele.nombrePlace }}</td>
            </tr>

            <tr><td class="label">Reponse :</td>
                <td style="background-color: lightsalmon">{{ modele.dateDebut|date }}</td>
            </tr>

            <tr><td class="label">Reponse :</td>
                <td style="background-color: lightsalmon">{{ modele.dateFin|date }}</td>
            </tr>

            <tr><td class="label">Reponse :</td>
                <td style="background-color: lightsalmon">{{ modele.user }}</td>
            </tr>

            <tr><td class="label">Date :</td>
                <td style="background-color: mintcream">{{ modele.date|date }}</td>
            </tr>
        </table>

    </div><br><br>


</center>
</div>
</body>
</html>

src/SocialPro/MainBundle/Resources/views/Evenement/try.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Simple markers</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        #map {
            height: 100%;
        }
    </style>
</head>
<body>
<center><div id="map" align="center" style="width: 900px;height: 900px;"></div></center>
<script>

    function initMap() {
        var myLatLng = {lat: -80.363, lng: 131.044};

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: myLatLng
        });

        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Hello World!'
        });
    }

</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCDST6BTwCnHvix1nBZuWO8SQtpmyu6-ys&signed_in=true&callback=initMap"></script>
</body>
</html>